name: Keep App Alive

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: curl -sSf -H "Authorization: Bearer $HF_TOKEN" "https://huggingface.co/spaces/luoguocheng/n8n-free"

